### ISSUE TITLE
error when running configure

### ISSUE THREAD

**Issue by louisj381** [UCSolarCarTeam/Epsilon-Raspberry#10]
Issue running line 116 of setupscript, command worked on my pi, however does not work on Bill's, does not successfully create make and qmake, causing final commands of script to fail. I will attach image of output 
file. `/usr/bin/ld: cannot open output file ../bin/qmake: No such file or directory`
I googled and double checked with wiki, even adding `-no-pch` but had same error, https://wiki.qt.io/Native_Build_of_Qt5_on_a_Raspberry_Pi
![img_20180113_153423](https://user-images.githubusercontent.com/23280852/34921073-702d2246-f93a-11e7-808a-e706771b4bd8.jpg)

**Comment by bill-luu** [comment]
I think I got it, using some instructions from [this](https://wiki.qt.io/RaspberryPi2EGLFS#Step_by_step) wiki.

- Use raspi-config to increase the ram to 512MB
- Update the Pi firmware
````
sudo rpi-update
reboot
````
- Uncommented the deb-src line
````
sudo nano /etc/apt/sources.list
````
- Installed some stuff
````
sudo apt-get update
sudo apt-get build-dep qt4-x11
sudo apt-get build-dep libqt5gui5
sudo apt-get install libudev-dev libinput-dev libts-dev libxcb-xinerama0-dev libxcb-xinerama0
````

**Comment by louisj381** [comment]
Tested, did the trick! Thanks @bill-luu
