### ISSUE TITLE
Configuring/Compiling Epsilon-Dashboard with current setup-script

### ISSUE THREAD

**Issue by louisj381** [UCSolarCarTeam/Epsilon-Raspberry#6]
ran the make file within the Epsilon-Dashboard directory
![exit_status](https://user-images.githubusercontent.com/23280852/33358756-cb845c72-d487-11e7-8e32-b65a1bdcfd88.jpg)

**Comment by ExtraGravity** [comment]
The error there is pretty clear `-lSimpleAmqpClient`. The rabbitmq interface libraries haven't been installed.

**Comment by bill-luu** [comment]
Try re-running the Dashboard's setup script, or if that doesn't work (we'll have to fix it) follow the steps in the Hermes wiki: https://github.com/UCSolarCarTeam/Epsilon-Hermes (Installing rabbitmq)
